


with cdc_src as (

    select __dbz_operation, __dbz_timestamp, __dbz_lsn, record_data
    from [eh_xboss].[dbo].[cdc_events]
    where __dbz_table  = 'account_move'
      and __dbz_schema = 'public'
    
      and __dbz_timestamp > (select COALESCE(MAX(__dbz_timestamp), cast('1970-01-01' as datetime2(6))) from [wh_core].[cc1].[stg_xboss_cdc__account_move])
    
),
cdc_keyed as (
    select
        __dbz_operation,
        __dbz_timestamp,
        __dbz_lsn,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), concat(coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_timestamp as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_lsn as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'))), '')), 2))
 as __event_key,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_')), '')), 2))
      as __id,
        j.*
    from cdc_src
    cross apply OPENJSON(record_data) with (
        [id] int            '$.id',
        [sequence_number] int            '$.sequence_number',
        [message_main_attachment_id] int            '$.message_main_attachment_id',
        [journal_id] int            '$.journal_id',
        [company_id] int            '$.company_id',
        [payment_id] int            '$.payment_id',
        [statement_line_id] int            '$.statement_line_id',
        [tax_cash_basis_rec_id] int            '$.tax_cash_basis_rec_id',
        [tax_cash_basis_origin_move_id] int            '$.tax_cash_basis_origin_move_id',
        [auto_post_origin_id] int            '$.auto_post_origin_id',
        [secure_sequence_number] int            '$.secure_sequence_number',
        [invoice_payment_term_id] int            '$.invoice_payment_term_id',
        [partner_id] int            '$.partner_id',
        [commercial_partner_id] int            '$.commercial_partner_id',
        [partner_shipping_id] int            '$.partner_shipping_id',
        [partner_bank_id] int            '$.partner_bank_id',
        [fiscal_position_id] int            '$.fiscal_position_id',
        [currency_id] int            '$.currency_id',
        [reversed_entry_id] int            '$.reversed_entry_id',
        [invoice_user_id] int            '$.invoice_user_id',
        [invoice_incoterm_id] int            '$.invoice_incoterm_id',
        [invoice_cash_rounding_id] int            '$.invoice_cash_rounding_id',
        [create_uid] int            '$.create_uid',
        [write_uid] int            '$.write_uid',
        [sequence_prefix] varchar(max)   '$.sequence_prefix',
        [access_token] varchar(max)   '$.access_token',
        [name] varchar(max)   '$.name',
        [ref] varchar(max)   '$.ref',
        [state] varchar(max)   '$.state',
        [move_type] varchar(max)   '$.move_type',
        [auto_post] varchar(max)   '$.auto_post',
        [inalterable_hash] varchar(max)   '$.inalterable_hash',
        [payment_reference] varchar(max)   '$.payment_reference',
        [qr_code_method] varchar(max)   '$.qr_code_method',
        [payment_state] varchar(max)   '$.payment_state',
        [invoice_source_email] varchar(max)   '$.invoice_source_email',
        [invoice_partner_display_name] varchar(max)   '$.invoice_partner_display_name',
        [invoice_origin] varchar(max)   '$.invoice_origin',
        [incoterm_location] varchar(max)   '$.incoterm_location',
        [date] int            '$.date',
        [auto_post_until] int            '$.auto_post_until',
        [invoice_date] int            '$.invoice_date',
        [invoice_date_due] int            '$.invoice_date_due',
        [delivery_date] int            '$.delivery_date',
        [send_and_print_values] varchar(max)   '$.send_and_print_values',
        [narration] varchar(max)   '$.narration',
        [amount_untaxed] decimal(38,10) '$.amount_untaxed',
        [amount_tax] decimal(38,10) '$.amount_tax',
        [amount_total] decimal(38,10) '$.amount_total',
        [amount_residual] decimal(38,10) '$.amount_residual',
        [amount_untaxed_signed] decimal(38,10) '$.amount_untaxed_signed',
        [amount_tax_signed] decimal(38,10) '$.amount_tax_signed',
        [amount_total_signed] decimal(38,10) '$.amount_total_signed',
        [amount_total_in_currency_signed] decimal(38,10) '$.amount_total_in_currency_signed',
        [amount_residual_signed] decimal(38,10) '$.amount_residual_signed',
        [quick_edit_total_amount] decimal(38,10) '$.quick_edit_total_amount',
        [is_storno] bit            '$.is_storno',
        [always_tax_exigible] bit            '$.always_tax_exigible',
        [to_check] bit            '$.to_check',
        [posted_before] bit            '$.posted_before',
        [is_move_sent] bit            '$.is_move_sent',
        [create_date] bigint         '$.create_date',
        [write_date] bigint         '$.write_date',
        [expense_sheet_id] int            '$.expense_sheet_id',
        [stock_move_id] int            '$.stock_move_id',
        [manual_entry] bit            '$.manual_entry',
        [post_date] bigint         '$.post_date',
        [campaign_id] int            '$.campaign_id',
        [source_id] int            '$.source_id',
        [medium_id] int            '$.medium_id',
        [team_id] int            '$.team_id',
        [countered] varchar(max)   '$.countered',
        [comment] varchar(max)   '$.comment',
        [amount_invoice_deduct] decimal(38,10) '$.amount_invoice_deduct',
        [amount_invoice_deduct_currency] decimal(38,10) '$.amount_invoice_deduct_currency',
        [is_opening] bit            '$.is_opening',
        [is_initial_balance] bit            '$.is_initial_balance',
        [is_advance] bit            '$.is_advance',
        [is_manyxmany] bit            '$.is_manyxmany',
        [auto_transfer_model_id] int            '$.auto_transfer_model_id',
        [legal_number] varchar(max)   '$.legal_number',
        [old_number] varchar(max)   '$.old_number',
        [countered_status] varchar(max)   '$.countered_status',
        [account_asset_id] int            '$.account_asset_id',
        [project_id] int            '$.project_id',
        [progress_bill_title] varchar(max)   '$.progress_bill_title',
        [total_progress_billing] float          '$.total_progress_billing',
        [invoice_to_date] float          '$.invoice_to_date',
        [remaining_progress_billing] float          '$.remaining_progress_billing',
        [previously_invoice] float          '$.previously_invoice',
        [previously_invoice_due] float          '$.previously_invoice_due',
        [current_invoice] float          '$.current_invoice',
        [less_paid_amount] float          '$.less_paid_amount',
        [total_due] float          '$.total_due',
        [inter_comp_invoice_id] int            '$.inter_comp_invoice_id',
        [stock_picking_id] int            '$.stock_picking_id',
        [job_cost_id] int            '$.job_cost_id',
        [edi_state] varchar(max)   '$.edi_state',
        [highest_name] varchar(max)   '$.highest_name',
        [made_sequence_hole] bit            '$.made_sequence_hole',
        [einvoice_issue_user_id] int            '$.einvoice_issue_user_id',
        [account_einvoice_serial_id] int            '$.account_einvoice_serial_id',
        [failed_cron_download_einvoice_file_times] int            '$.failed_cron_download_einvoice_file_times',
        [l10n_vn_edi_representation_pdf_filename] varchar(max)   '$.l10n_vn_edi_representation_pdf_filename',
        [l10n_vn_edi_official_representation_filename] varchar(max)   '$.l10n_vn_edi_official_representation_filename',
        [l10n_vn_edi_converted_filename] varchar(max)   '$.l10n_vn_edi_converted_filename',
        [einvoice_transactionid] varchar(max)   '$.einvoice_transactionid',
        [l10n_vn_edi_adjust_desc] varchar(max)   '$.l10n_vn_edi_adjust_desc',
        [l10n_vn_edi_cancel_desc] varchar(max)   '$.l10n_vn_edi_cancel_desc',
        [einvoice_invoice_date] bigint         '$.einvoice_invoice_date',
        [l10n_vn_edi_cancel_date] bigint         '$.l10n_vn_edi_cancel_date',
        [sinvoice_state] varchar(max)   '$.sinvoice_state',
        [sinvoice_reservation_code] varchar(max)   '$.sinvoice_reservation_code',
        [custom_construction_ipc_id] int            '$.custom_construction_ipc_id',
        [sinvoice_is_construction] bit            '$.sinvoice_is_construction',
        [analytic_distribution] varchar(max)   '$.analytic_distribution',
        [requisition_id] int            '$.requisition_id',
        [inspection_job_card_id] int            '$.inspection_job_card_id',
        [repair_job_card_id] int            '$.repair_job_card_id',
        [sinvoice_origin_legal_number] varchar(max)   '$.sinvoice_origin_legal_number',
        [sinvoice_origin_issue_date] bigint         '$.sinvoice_origin_issue_date',
        [posted_user_id] int            '$.posted_user_id',
        [sinvoice_adjustment_note] varchar(max)   '$.sinvoice_adjustment_note',
        [sinvoice_discount_only_display_total] bit            '$.sinvoice_discount_only_display_total',
        [force_pass_unique_ref] bit            '$.force_pass_unique_ref',
        [property_id] int            '$.property_id',
        [new_tenancy_id] int            '$.new_tenancy_id',
        [asset_id] int            '$.asset_id',
        [tenancy_rent_schedule_id] int            '$.tenancy_rent_schedule_id',
        [source] varchar(max)   '$.source',
        [schedule_date] int            '$.schedule_date',
        [start_date] int            '$.start_date',
        [end_date] int            '$.end_date',
        [sinvoice_origin_move_id] int            '$.sinvoice_origin_move_id',
        [sinvoice_replace_note] varchar(max)   '$.sinvoice_replace_note',
        [sinvoice_adjustment_type] varchar(max)   '$.sinvoice_adjustment_type',
        [is_ready_apr] bit            '$.is_ready_apr',
        [sinvoice_adjustment_invoice_type] varchar(max)   '$.sinvoice_adjustment_invoice_type',
        [main_attachment_id] int            '$.main_attachment_id',
        [debit_origin_id] int            '$.debit_origin_id',
        [is_sinvoice_tax_adjustment] bit            '$.is_sinvoice_tax_adjustment',
        [allow_sync_zero_line] bit            '$.allow_sync_zero_line',
        [sinvoice_origin_buyer_name] varchar(max)   '$.sinvoice_origin_buyer_name',
        [sinvoice_origin_buyer_address] varchar(max)   '$.sinvoice_origin_buyer_address',
        [sinvoice_origin_buyer_tax_code] varchar(max)   '$.sinvoice_origin_buyer_tax_code',
        [sinvoice_origin_buyer_phone] varchar(max)   '$.sinvoice_origin_buyer_phone',
        [sinvoice_origin_buyer_email] varchar(max)   '$.sinvoice_origin_buyer_email',
        [sinvoice_buyer_name] varchar(max)   '$.sinvoice_buyer_name',
        [sinvoice_buyer_address] varchar(max)   '$.sinvoice_buyer_address',
        [sinvoice_buyer_tax_code] varchar(max)   '$.sinvoice_buyer_tax_code',
        [sinvoice_buyer_phone] varchar(max)   '$.sinvoice_buyer_phone',
        [sinvoice_buyer_email] varchar(max)   '$.sinvoice_buyer_email',
        [opening_entries] bit            '$.opening_entries',
        [is_property_rent] bit            '$.is_property_rent',
        [is_linked_apr] bit            '$.is_linked_apr',
        [x_workflow_state] varchar(max)   '$.x_workflow_state',
        [x_workflow_approve_user] varchar(max)   '$.x_workflow_approve_user',
        [x_workflow_id] int            '$.x_workflow_id',
        [x_workflow_state_date] bigint         '$.x_workflow_state_date',
        [x_workflow_stage_id] int            '$.x_workflow_stage_id',
        [description] varchar(max)   '$.description',
        [sinvoice_payment_method] varchar(max)   '$.sinvoice_payment_method',
        [sinvoice_payment_method_name] varchar(max)   '$.sinvoice_payment_method_name',
        [sinvoice_replacement_email] varchar(max)   '$.sinvoice_replacement_email',
        [x_workflow_config_id] int            '$.x_workflow_config_id',
        [serial_no] varchar(max)   '$.serial_no',
        [tax_description] varchar(max)   '$.tax_description',
        [failed_cron_download_einvoice_representation_file_times] int            '$.failed_cron_download_einvoice_representation_file_times',
        [manual_spread_template_id] int            '$.manual_spread_template_id',
        [x_pms_send_email_bill_on_approve] bit            '$.x_pms_send_email_bill_on_approve',
        [custom_declaration_import_id] int            '$.custom_declaration_import_id',
        [manual_currency_rate] decimal(38,10) '$.manual_currency_rate',
        [manual_currency_rate_active] bit            '$.manual_currency_rate_active',
        [joint_venture_id] int            '$.joint_venture_id',
        [is_joint_venture_agreement] bit            '$.is_joint_venture_agreement'
    ) as j
)

select * from cdc_keyed
