


with cdc_src as (

    select __dbz_operation, __dbz_timestamp, __dbz_lsn, record_data
    from [eh_xboss].[dbo].[cdc_events]
    where __dbz_table  = 'hr_employee'
      and __dbz_schema = 'public'
    
      and __dbz_timestamp > (select COALESCE(MAX(__dbz_timestamp), cast('1970-01-01' as datetime2(6))) from [wh_core].[cc1].[stg_xboss_cdc__hr_employee])
    
),
cdc_keyed as (
    select
        __dbz_operation,
        __dbz_timestamp,
        __dbz_lsn,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), concat(coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_timestamp as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_lsn as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'))), '')), 2))
 as __event_key,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_')), '')), 2))
      as __id,
        j.*
    from cdc_src
    cross apply OPENJSON(record_data) with (
        [id] int            '$.id',
        [resource_id] int            '$.resource_id',
        [company_id] int            '$.company_id',
        [resource_calendar_id] int            '$.resource_calendar_id',
        [message_main_attachment_id] int            '$.message_main_attachment_id',
        [color] int            '$.color',
        [department_id] int            '$.department_id',
        [job_id] int            '$.job_id',
        [address_id] int            '$.address_id',
        [work_contact_id] int            '$.work_contact_id',
        [work_location_id] int            '$.work_location_id',
        [user_id] int            '$.user_id',
        [parent_id] int            '$.parent_id',
        [coach_id] int            '$.coach_id',
        [private_state_id] int            '$.private_state_id',
        [private_country_id] int            '$.private_country_id',
        [country_id] int            '$.country_id',
        [children] int            '$.children',
        [country_of_birth] int            '$.country_of_birth',
        [bank_account_id] int            '$.bank_account_id',
        [km_home_work] int            '$.km_home_work',
        [departure_reason_id] int            '$.departure_reason_id',
        [create_uid] int            '$.create_uid',
        [write_uid] int            '$.write_uid',
        [name] varchar(max)   '$.name',
        [job_title] varchar(max)   '$.job_title',
        [work_phone] varchar(max)   '$.work_phone',
        [mobile_phone] varchar(max)   '$.mobile_phone',
        [work_email] varchar(max)   '$.work_email',
        [private_street] varchar(max)   '$.private_street',
        [private_street2] varchar(max)   '$.private_street2',
        [private_city] varchar(max)   '$.private_city',
        [private_zip] varchar(max)   '$.private_zip',
        [private_phone] varchar(max)   '$.private_phone',
        [private_email] varchar(max)   '$.private_email',
        [lang] varchar(max)   '$.lang',
        [gender] varchar(max)   '$.gender',
        [marital] varchar(max)   '$.marital',
        [spouse_complete_name] varchar(max)   '$.spouse_complete_name',
        [place_of_birth] varchar(max)   '$.place_of_birth',
        [ssnid] varchar(max)   '$.ssnid',
        [sinid] varchar(max)   '$.sinid',
        [identification_id] varchar(max)   '$.identification_id',
        [passport_id] varchar(max)   '$.passport_id',
        [permit_no] varchar(max)   '$.permit_no',
        [visa_no] varchar(max)   '$.visa_no',
        [certificate] varchar(max)   '$.certificate',
        [study_field] varchar(max)   '$.study_field',
        [study_school] varchar(max)   '$.study_school',
        [emergency_contact] varchar(max)   '$.emergency_contact',
        [emergency_phone] varchar(max)   '$.emergency_phone',
        [employee_type] varchar(max)   '$.employee_type',
        [barcode] varchar(max)   '$.barcode',
        [pin] varchar(max)   '$.pin',
        [private_car_plate] varchar(max)   '$.private_car_plate',
        [spouse_birthdate] int            '$.spouse_birthdate',
        [birthday] int            '$.birthday',
        [visa_expire] int            '$.visa_expire',
        [work_permit_expiration_date] int            '$.work_permit_expiration_date',
        [departure_date] int            '$.departure_date',
        [employee_properties] varchar(max)   '$.employee_properties',
        [additional_note] varchar(max)   '$.additional_note',
        [notes] varchar(max)   '$.notes',
        [departure_description] varchar(max)   '$.departure_description',
        [active] bit            '$.active',
        [work_permit_scheduled_activity] bit            '$.work_permit_scheduled_activity',
        [create_date] bigint         '$.create_date',
        [write_date] bigint         '$.write_date',
        [vat] varchar(max)   '$.vat',
        [place_of_origin] varchar(max)   '$.place_of_origin',
        [mobility_card] varchar(max)   '$.mobility_card',
        [hourly_cost] decimal(38,10) '$.hourly_cost',
        [x_code] varchar(max)   '$.x_code',
        [expense_manager_id] int            '$.expense_manager_id',
        [start_working_date] int            '$.start_working_date',
        [grade_id] int            '$.grade_id',
        [role_id] int            '$.role_id',
        [rank_id] int            '$.rank_id',
        [next_rank_id] int            '$.next_rank_id',
        [job_position_skills_required] bit            '$.job_position_skills_required',
        [code] varchar(max)   '$.code',
        [annual_leave_days] int            '$.annual_leave_days',
        [attendance_manager_id] int            '$.attendance_manager_id',
        [last_attendance_id] int            '$.last_attendance_id',
        [last_check_in] bigint         '$.last_check_in',
        [last_check_out] bigint         '$.last_check_out',
        [contract_id] int            '$.contract_id',
        [vehicle] varchar(max)   '$.vehicle',
        [first_contract_date] int            '$.first_contract_date',
        [contract_warning] bit            '$.contract_warning',
        [leave_manager_id] int            '$.leave_manager_id',
        [other_dependant] int            '$.other_dependant',
        [total_dependant] int            '$.total_dependant',
        [emergency_relation_type] varchar(max)   '$.emergency_relation_type',
        [religion_id] int            '$.religion_id',
        [ethnic_id] int            '$.ethnic_id',
        [permanent_country_id] int            '$.permanent_country_id',
        [permanent_state_id] int            '$.permanent_state_id',
        [permanent_district_id] int            '$.permanent_district_id',
        [permanent_ward_id] int            '$.permanent_ward_id',
        [temporary_country_id] int            '$.temporary_country_id',
        [temporary_state_id] int            '$.temporary_state_id',
        [temporary_district_id] int            '$.temporary_district_id',
        [temporary_ward_id] int            '$.temporary_ward_id',
        [permanent_street] varchar(max)   '$.permanent_street',
        [temporary_street] varchar(max)   '$.temporary_street',
        [insurance_health_code] varchar(max)   '$.insurance_health_code',
        [identification_place] varchar(max)   '$.identification_place',
        [passport_place] varchar(max)   '$.passport_place',
        [social_insurance_date] int            '$.social_insurance_date',
        [health_insurance_date] int            '$.health_insurance_date',
        [join_union_date] int            '$.join_union_date',
        [deduction_itself_date] int            '$.deduction_itself_date',
        [maternity_leave_start_date] int            '$.maternity_leave_start_date',
        [maternity_leave_end_date] int            '$.maternity_leave_end_date',
        [identification_date] int            '$.identification_date',
        [identification_expire_date] int            '$.identification_expire_date',
        [passport_date] int            '$.passport_date',
        [passport_expire_date] int            '$.passport_expire_date',
        [has_maternity_leave] bit            '$.has_maternity_leave',
        [employee_token] varchar(max)   '$.employee_token',
        [created_from_attendance_device] bit            '$.created_from_attendance_device',
        [manual_attendance_manager_id] int            '$.manual_attendance_manager_id',
        [first_non_trial_contract_date] int            '$.first_non_trial_contract_date',
        [termination_date] int            '$.termination_date',
        [advance_account_id] int            '$.advance_account_id',
        [overtime_manager_id] int            '$.overtime_manager_id',
        [administrative_region_id] int            '$.administrative_region_id',
        [salary_to_bank] bit            '$.salary_to_bank',
        [department_manager_id] int            '$.department_manager_id',
        [department_parent_manager_id] int            '$.department_parent_manager_id',
        [home_town] varchar(max)   '$.home_town',
        [spouse_mobile] varchar(max)   '$.spouse_mobile',
        [identity_card_id] varchar(max)   '$.identity_card_id',
        [identity_card_place] varchar(max)   '$.identity_card_place',
        [employee_option] varchar(max)   '$.employee_option',
        [identity_card_date] int            '$.identity_card_date',
        [identity_card_expire_date] int            '$.identity_card_expire_date',
        [has_accident_insruance] bit            '$.has_accident_insruance',
        [request_id] int            '$.request_id',
        [hospital_id] int            '$.hospital_id',
        [recommender] varchar(max)   '$.recommender',
        [deformity] varchar(max)   '$.deformity',
        [has_deformity] bit            '$.has_deformity',
        [weight] float          '$.weight',
        [height] float          '$.height',
        [dyob] int            '$.dyob',
        [mob] int            '$.mob',
        [yob] int            '$.yob',
        [hr_employee_resignations_count] int            '$.hr_employee_resignations_count',
        [resigned] bit            '$.resigned',
        [last_appraisal_id] int            '$.last_appraisal_id',
        [ongoing_appraisal_count] int            '$.ongoing_appraisal_count',
        [appraisal_count] int            '$.appraisal_count',
        [next_appraisal_date] int            '$.next_appraisal_date',
        [last_appraisal_date] int            '$.last_appraisal_date',
        [is_manual_input_first_contract_date] bit            '$.is_manual_input_first_contract_date',
        [dest_location_id] int            '$.dest_location_id'
    ) as j
)

select * from cdc_keyed
