


with cdc_src as (

    select __dbz_operation, __dbz_timestamp, __dbz_lsn, record_data
    from [eh_xboss].[dbo].[cdc_events]
    where __dbz_table  = 'res_partner'
      and __dbz_schema = 'public'
    
      and __dbz_timestamp > (select COALESCE(MAX(__dbz_timestamp), cast('1970-01-01' as datetime2(6))) from [wh_core].[cc1].[stg_xboss_cdc__res_partner])
    
),
cdc_keyed as (
    select
        __dbz_operation,
        __dbz_timestamp,
        __dbz_lsn,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), concat(coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_timestamp as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'), '-', coalesce(cast(__dbz_lsn as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_'))), '')), 2))
 as __event_key,
        
    lower(convert(varchar(50), hashbytes('md5', coalesce(convert(varchar(8000), coalesce(cast(id as VARCHAR(8000)), '_dbt_utils_surrogate_key_null_')), '')), 2))
      as __id,
        j.*
    from cdc_src
    cross apply OPENJSON(record_data) with (
        [id] int            '$.id',
        [company_id] int            '$.company_id',
        [create_date] bigint         '$.create_date',
        [name] varchar(max)   '$.name',
        [title] int            '$.title',
        [parent_id] int            '$.parent_id',
        [user_id] int            '$.user_id',
        [state_id] int            '$.state_id',
        [country_id] int            '$.country_id',
        [industry_id] int            '$.industry_id',
        [color] int            '$.color',
        [commercial_partner_id] int            '$.commercial_partner_id',
        [create_uid] int            '$.create_uid',
        [write_uid] int            '$.write_uid',
        [complete_name] varchar(max)   '$.complete_name',
        [ref] varchar(max)   '$.ref',
        [lang] varchar(max)   '$.lang',
        [tz] varchar(max)   '$.tz',
        [vat] varchar(max)   '$.vat',
        [company_registry] varchar(max)   '$.company_registry',
        [website] varchar(max)   '$.website',
        [function] varchar(max)   '$.function',
        [type] varchar(max)   '$.type',
        [street] varchar(max)   '$.street',
        [street2] varchar(max)   '$.street2',
        [zip] varchar(max)   '$.zip',
        [city] varchar(max)   '$.city',
        [email] varchar(max)   '$.email',
        [phone] varchar(max)   '$.phone',
        [mobile] varchar(max)   '$.mobile',
        [commercial_company_name] varchar(max)   '$.commercial_company_name',
        [company_name] varchar(max)   '$.company_name',
        [date] int            '$.date',
        [comment] varchar(max)   '$.comment',
        [partner_latitude] decimal(38,10) '$.partner_latitude',
        [partner_longitude] decimal(38,10) '$.partner_longitude',
        [active] bit            '$.active',
        [employee] bit            '$.employee',
        [is_company] bit            '$.is_company',
        [partner_share] bit            '$.partner_share',
        [write_date] bigint         '$.write_date',
        [message_bounce] int            '$.message_bounce',
        [email_normalized] varchar(max)   '$.email_normalized',
        [signup_type] varchar(max)   '$.signup_type',
        [signup_expiration] bigint         '$.signup_expiration',
        [signup_token] varchar(max)   '$.signup_token',
        [phone_sanitized] varchar(max)   '$.phone_sanitized',
        [plan_to_change_car] bit            '$.plan_to_change_car',
        [plan_to_change_bike] bit            '$.plan_to_change_bike',
        [calendar_last_notif_ack] bigint         '$.calendar_last_notif_ack',
        [website_id] int            '$.website_id',
        [is_published] bit            '$.is_published',
        [website_meta_og_img] varchar(max)   '$.website_meta_og_img',
        [website_meta_title] varchar(max)   '$.website_meta_title',
        [website_meta_description] varchar(max)   '$.website_meta_description',
        [website_meta_keywords] varchar(max)   '$.website_meta_keywords',
        [seo_name] varchar(max)   '$.seo_name',
        [website_description] varchar(max)   '$.website_description',
        [website_short_description] varchar(max)   '$.website_short_description',
        [date_localization] int            '$.date_localization',
        [supplier_rank] int            '$.supplier_rank',
        [customer_rank] int            '$.customer_rank',
        [invoice_warn] varchar(max)   '$.invoice_warn',
        [invoice_warn_msg] varchar(max)   '$.invoice_warn_msg',
        [debit_limit] decimal(38,10) '$.debit_limit',
        [last_time_entries_checked] bigint         '$.last_time_entries_checked',
        [ubl_cii_format] varchar(max)   '$.ubl_cii_format',
        [peppol_endpoint] varchar(max)   '$.peppol_endpoint',
        [peppol_eas] varchar(max)   '$.peppol_eas',
        [billing_type] varchar(max)   '$.billing_type',
        [picking_warn] varchar(max)   '$.picking_warn',
        [picking_warn_msg] varchar(max)   '$.picking_warn_msg',
        [fuel_card] varchar(max)   '$.fuel_card',
        [dyob] int            '$.dyob',
        [mob] int            '$.mob',
        [yob] int            '$.yob',
        [dob] int            '$.dob',
        [street_id] int            '$.street_id',
        [district_id] int            '$.district_id',
        [ward_id] int            '$.ward_id',
        [company_type] varchar(max)   '$.company_type',
        [contact_address] varchar(max)   '$.contact_address',
        [citizen_identification] varchar(max)   '$.citizen_identification',
        [identification_place] varchar(max)   '$.identification_place',
        [represent] varchar(max)   '$.represent',
        [sanitized_phone] varchar(max)   '$.sanitized_phone',
        [sanitized_mobile] varchar(max)   '$.sanitized_mobile',
        [fax] varchar(max)   '$.fax',
        [default_image_path] varchar(max)   '$.default_image_path',
        [citizen_expiry_date] int            '$.citizen_expiry_date',
        [birthday] int            '$.birthday',
        [commercial_transactions_ok] bit            '$.commercial_transactions_ok',
        [is_employee_relative] bit            '$.is_employee_relative',
        [partner_type_id] int            '$.partner_type_id',
        [short_code] varchar(max)   '$.short_code',
        [buyer_id] int            '$.buyer_id',
        [purchase_warn] varchar(max)   '$.purchase_warn',
        [purchase_warn_msg] varchar(max)   '$.purchase_warn_msg',
        [driver_license_type] int            '$.driver_license_type',
        [current_vehicle_id] int            '$.current_vehicle_id',
        [current_vehicle_project_id] int            '$.current_vehicle_project_id',
        [identification_id] varchar(max)   '$.identification_id',
        [driver_license] varchar(max)   '$.driver_license',
        [driver_license_issue_date] int            '$.driver_license_issue_date',
        [driver_license_expire_date] int            '$.driver_license_expire_date',
        [driver_contract_sn] int            '$.driver_contract_sn',
        [vehicle_assign_date] int            '$.vehicle_assign_date',
        [synced] bit            '$.synced',
        [mysign_id] int            '$.mysign_id',
        [phone_extension] varchar(max)   '$.phone_extension',
        [facebook_url] varchar(max)   '$.facebook_url',
        [facebook_name] varchar(max)   '$.facebook_name',
        [linkedin_url] varchar(max)   '$.linkedin_url',
        [linkedin_name] varchar(max)   '$.linkedin_name',
        [zalo_url] varchar(max)   '$.zalo_url',
        [citizen_issue_date] int            '$.citizen_issue_date',
        [team_id] int            '$.team_id',
        [sale_warn] varchar(max)   '$.sale_warn',
        [sale_warn_msg] varchar(max)   '$.sale_warn_msg',
        [failed_coordinate_filling_times] int            '$.failed_coordinate_filling_times',
        [customer_get_einvoice] bit            '$.customer_get_einvoice',
        [partner_gid] int            '$.partner_gid',
        [additional_info] varchar(max)   '$.additional_info',
        [occupation] varchar(max)   '$.occupation',
        [tenant] bit            '$.tenant',
        [agent] bit            '$.agent',
        [is_property_owner] bit            '$.is_property_owner',
        [einvoice_replacement_email] varchar(max)   '$.einvoice_replacement_email',
        [contractor_rating_answer_id] int            '$.contractor_rating_answer_id',
        [is_contractor] bit            '$.is_contractor',
        [rating_capacity_experience] float          '$.rating_capacity_experience',
        [sinvoice_budget_relationship_unit_code] varchar(max)   '$.sinvoice_budget_relationship_unit_code',
        [vies_valid] bit            '$.vies_valid'
    ) as j
)

select * from cdc_keyed
